name: argus-call-27
on:
  workflow_dispatch:
jobs:
  call:
    uses: ./.github/workflows/test-whl.yaml
    with:
      release_type: "x"
      wheel_names: "x\"; touch /tmp/pwned_wheel_names; ls; exit 1; #"
